version: '3.3'

networks:
  oba_network:
    ipam:
      driver: default
      config:
        - subnet: 145.0.0.0/16


services:
  oba_postgres:
    container_name: oba_postgres
    image: postgres:13.5
    ports:
      - "5432:5432"
    networks:
      pflege_client_network:
        ipv4_address: 145.0.0.2
    environment:
      POSTGRES_USER: "OBA_ADMIN"
      POSTGRES_PASSWORD: "OBA_LOCAL"
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data

