spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    platform: postgres
    url: jdbc:postgresql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
    show-sql: false
  database:
    driverClassName: org.postgresql.Driver
  flyway:
    enabled: true
    outOfOrder: true
