spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: OBA_ADMIN
    password: OBA_LOCAL
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  database:
    driverClassName: org.postgresql.Driver
